# A configuration file is required for this project, like mysql/git configuration etc...
# Because some configurations involve security, they cannot be disclosed. You should create "config.yaml" under this project by yourself.
# All configuration information keys is in /tirelease/commons/configs/config.go in struct of ConfigYaml
# Config like this:
tidb:
  username: ***
  password: ***
  host: ***
  port: "***"
  database: ***
  charset: ***
  timezone: ***

